### ISSUE TITLE
Graphical issues with Iris and Indium 1.0.19+

### ISSUE THREAD

**Issue by dbrighthd** [comp500/Indium#210]
![image](https://github.com/comp500/Indium/assets/68525639/11466946-c1cc-4915-8dd7-d3a52828c017)
![image](https://github.com/comp500/Indium/assets/68525639/38954663-f5ae-445d-b05e-27fd8f7a2bc3)

light leaks on the side of blocks with 1.0.20, but not with 1.0.18

**Comment by ertugrulahmett** [comment]
last update break my complementary shaders too,

here is same screenshot with 2 different indium versions (1.0.18 - 1.0.20)

![2023-07-10_12 56 39](https://github.com/comp500/Indium/assets/56203005/4ff78ac3-6d0d-4861-ba31-5d14b66d72b9)

![2023-07-10_12 53 31](https://github.com/comp500/Indium/assets/56203005/c1cd4e65-fd24-48a8-aace-8a97ae3ad538)

**Comment by IMS212** [comment]
This is an Iris issue and will be fixed in the next update.

**Comment by Oguzhan5585** [comment]
new iris version came out, so this should be fixed now i guess.

**Comment by iblowmymind** [comment]
I still get this issue, though, with or without shaders:
![image](https://github.com/comp500/Indium/assets/28228415/38ff503f-3d67-47bf-8151-fd4ca27c8d75)

Can the issue be reopened?

**Comment by Oguzhan5585** [comment]
@IMS212 ?

**Comment by comp500** [comment]
That is not the same issue, see #220

**Comment by ertugrulahmett** [comment]
> new iris version came out, so this should be fixed now i guess.

Yeah its fixed thanks
